# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- feature-ms-eduardoChasco-mensaje

pool:
  vmImage: ubuntu-latest

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudEC'
    organization: 'devops-trabajofinal-ec'
    projectKey: 'DevOps-TrabajoFinal-EC_microservicio-spring'
    projectName: 'microservicio-spring'
    scannerMode: 'Other'
  displayName: 'SonarCloud Prepare'
  
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: false
#   testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
#   jdkVersionOption: '1.8'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
  displayName: 'Gradle'