jobs:
- job:
  pool:
    vmImage: ubuntu-latest
  displayName: Build

  steps: 
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
    displayName: Build
  - task: Gradle@2
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)'
      gradleWrapperFile: 'gradlew'
      tasks: 'test'
      publishJUnitResults: true
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      testResultsFiles: '**/build/test-results/test/*.xml'
    displayName: 'JUnit'

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      testRunTitle: 'Coverage'
      codeCoverageToolOption: 'Cobertura'
      codeCoverageClassFilesDirectories: 'build/classes/main/'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
    displayName: 'Cobertura'
  #- task: SonarCloudPrepare@1
  #  inputs:
  #    SonarCloud: 'SonarCloudEC'
  #    organization: 'devops-trabajofinal-ec'
  #    projectKey: 'DevOps-TrabajoFinal-EC_microservicio-spring'
  #    projectName: 'microservicio-spring'
  #  displayName: 'SonarCloud Prepare'

  #- task: Gradle@3
  #  inputs:
  #    gradleWrapperFile: 'gradlew'
  #    tasks: 'sonar'
  #    publishJUnitResults: true
  #    testResultsFiles: '**/TEST-*.xml'
  #    codeCoverageToolOption: 'JaCoCo'
  #    codeCoverageClassFilesDirectories: 'build/classes/main/'
  #    codeCoverageGradle5xOrHigher: false
  #    javaHomeOption: 'JDKVersion'
  #    sonarQubeRunAnalysis: true
  #    sqGradlePluginVersionChoice: 'specify'
  #    sonarQubeGradlePluginVersion: '3.3'
  #    spotBugsAnalysis: false
  #  displayName: 'SonarCloud Analysis'

  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHub'
      command: 'login'
    displayName: 'Docker Login'
  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'nsg2020/microservicio-spring'
      command: 'build'
      Dockerfile: '**/Dockerfile'
    displayName: 'Docker Build'

  - task: Docker@2
    inputs:
      containerRegistry: 'DockerHub'
      repository: 'nsg2020/microservicio-spring'
      command: 'push'
    displayName: 'Docker Push'
