pool:
  vmImage: ubuntu-latest

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudEC'
    organization: 'devops-trabajofinal-ec'
    projectKey: 'DevOps-TrabajoFinal-EC_microservicio-spring'
    projectName: 'microservicio-spring'
  displayName: 'SonarCloud Prepare'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build jacocoTestReport'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
  displayName: 'Build'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: 'build/reports/jacoco/test/jacocoTestReport.xml'
    reportDirectory: 'build/reports/jacoco/test'
    failIfCoverageEmpty: true
  displayName: 'Publish code coverage results'
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/results.jtl'